language: csharp
os: linux
dist: xenial
sudo: required
# dotnet: 3.1.201
mono: none

# cache:
#   yarn: true

addons:
  snaps:
  - name: dotnet-sdk
    classic: true
    channel: latest/stable

before_script:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - nvm install node
  - nvm use node
  # # Update npm
  # - npm install -g npm

script:
  - dotnet --version
  - node --version
  - dotnet fsi build.fsx test
